#!/usr/bin/env bash

version=`grep ^version metadata.rb | awk '{ print $2 }' | sed -e "s/'/'v/" -e "s/'//g"`
cookbook=$(basename $(pwd))
echo "Releasing $version of $cookbook"
hub release create $version
